### PR TITLE
Use DS components

### PR DESCRIPTION
**Pull request by ifvictr**

### CODE REVIEW

**Comment by zanedb** [comment]
Product names, i.e. “Cactus” aren’t rendering in the search field for me. Using Chrome on Android currently.

**Comment by ifvictr** [comment]
@merelinguist Had time to look at this yet?

**Comment by ifvictr** [comment]
@merelinguist Both have been fixed.

**Comment by merelinguist** [comment]
@ifvictr Thanks for this! I’ll fix the merge conflicts tomorrow morning and then this is ready to go.

**Comment by zanedb** [comment]
Search has since been rewritten in #7 :)

**Pull request closed without merging**
