### PR TITLE
Link to Shop homepage

### PR DESCRIPTION
**Pull request by ifvictr**
Makes more sense since header links like that usually link to the homepage of the domain they're on.

### CODE REVIEW

**Comment by zanedb** [comment]
Could you use the Gatsby Link component, with `to="/"` instead?

**Comment by zanedb** [comment]
Overall, I'm not sure if the navbar should work this way. I believe @zachlatta wanted it to.

**Comment by zachlatta** [comment]
@lachlanjc can you take point here?

--
Zach Latta

https://zachlatta.com ( http://zachlatta.com )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://www.facebook.com/crynix ) / github ( https://github.com/zachlatta )

**Comment by lachlanjc** [comment]
Sorry, not clear on what the desired outcome is here?

**Comment by zachlatta** [comment]
This is re: previous discussion we had on whether flag in top left should link to main site or Hack Club homepage. I’m pro homepage, but wanted to hand this PR off to you because it’s your codebase.

--
Zach Latta

https://zachlatta.com ( http://zachlatta.com )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://www.facebook.com/crynix ) / github ( https://github.com/zachlatta )

**Comment by lachlanjc** [comment]
Closing as this was added

**Pull request closed without merging**
